import { Link, useRouterState } from '@tanstack/react-router';
import { useCallback, useState, type ReactNode } from 'react';
import { Home, BookOpen, PlaySquare, ClipboardCheck, Box, Bookmark, Globe, Search, Sparkles, ArrowUpRight, Menu, X, Bell, ChevronDown, Orbit, ShieldCheck, LogOut } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { StarField } from './star-field';
import { Intro } from './intro';
import { AuthGate } from './auth-gate';
import { useAuth } from '@/lib/auth';

export function AstraShell({children}:{children:ReactNode}) {
 const [intro,setIntro]=useState(true);const [menu,setMenu]=useState(false);const [search,setSearch]=useState('');const [notice,setNotice]=useState(false);
 const {profile,signOut}=useAuth();const unlocked=profile?.status==='approved';const isAdmin=unlocked&&profile?.role==='admin';
 const pathname=useRouterState({select:s=>s.location.pathname});
 const closeIntro=useCallback(()=>setIntro(false),[]);
 const nav=[{name:'Bosh sahifa',icon:Home,to:'/' as const,mode:undefined},{name:'Fanlar',icon:BookOpen,to:'/fanlar' as const,mode:undefined},{name:'Darslar',icon:PlaySquare,to:'/fanlar' as const,mode:'darslar'},{name:'Testlar',icon:ClipboardCheck,to:'/fanlar' as const,mode:'testlar'},{name:'3D modellar',icon:Box,to:'/fanlar' as const,mode:'modellar'},{name:'Saqlanganlar',icon:Bookmark,to:'/fanlar' as const,mode:'saqlanganlar'}];
 return <div className="astra-app"><StarField/><aside className={`sidebar ${menu?'sidebar-open':''}`}><Link to="/" className="brand"><img src="/favicon.svg" alt=""/><span>ASTRA</span></Link><nav className={unlocked?'':'pointer-events-none opacity-40'}>{nav.map(n=><Button key={n.name} variant="nav" asChild><Link to={n.to} search={n.to==='/fanlar'?{mode:n.mode,q:undefined}:{}} className={(pathname===n.to&&!n.mode)?'nav-active':''} onClick={()=>setMenu(false)}><n.icon/><span>{n.name}</span>{n.name==='Fanlar'&&<ChevronDown className="nav-chevron"/>}</Link></Button>)}</nav>{isAdmin&&<Button variant="nav" asChild><Link to="/admin" className={pathname==='/admin'?'nav-active':''} onClick={()=>setMenu(false)}><ShieldCheck/><span>Admin panel</span></Link></Button>}<div className="sidebar-promo"><Sparkles/><h3>Bilim — bu kelajak</h3><p>Orzularingizga erishish uchun bugun o‘rganing!</p><Button variant="cosmic" size="sm" asChild><Link to="/fanlar">Darsni boshlash <ArrowUpRight/></Link></Button></div><div className="sidebar-bottom"><span><Globe/> O‘zbek <ChevronDown/></span><Button variant="nav" onClick={()=>setIntro(true)}><Orbit/> Intro ko‘rish</Button></div></aside>
 <div className="app-content"><header className="topbar"><Button variant="ghost" size="icon" className="mobile-menu" aria-label={menu?'Menyuni yopish':'Menyuni ochish'} onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</Button><form className="search-box" action="/fanlar"><Search/><input name="q" aria-label="Fan qidirish" placeholder="Fan, mavzu yoki dars izlang…" value={search} onChange={e=>setSearch(e.target.value)}/><span>⌘ K</span></form><div className="topbar-actions"><span className="online-label"><i/> Bilim olami</span><Button variant="ghost" size="icon" aria-label="Bildirishnomalar" onClick={()=>setNotice(v=>!v)}><Bell/></Button><div className="user-avatar">{(profile?.full_name??'A').charAt(0).toUpperCase()}</div><div className="user-label"><strong>{profile?.full_name??'ASTRA mehmoni'}</strong><small>{isAdmin?'Administrator':unlocked?'O‘quvchi':'Tasdiq kutilmoqda'}</small></div>{profile&&<Button variant="ghost" size="icon" aria-label="Chiqish" onClick={()=>void signOut()}><LogOut/></Button>}</div>{notice&&<div className="notification"><strong>ASTRA’ga xush kelibsiz!</strong><p>8 ta fan olami sizni kutmoqda.</p></div>}</header><main>{unlocked?children:<AuthGate/>}</main><footer className="app-footer"><Link to="/" className="brand"><img src="/favicon.svg" alt=""/><span>ASTRA<small>Ta’limning yangi olami</small></span></Link><span><strong>8</strong> Fanlar</span><span><strong>∞</strong> Imkoniyatlar</span><span className="footer-motto">Yulduzlar sari birga… <Sparkles/></span><Button variant="glass" size="sm" onClick={()=>setIntro(true)}><PlaySquare/> Intro</Button></footer></div>{intro&&<Intro onClose={closeIntro}/>}</div>;
}